name: Retrieve secrets from secret repo
on:
  workflow_dispatch:

jobs:
  retrieve-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Environment
        env:
          GARANT_ADMIN_PASSWORD: ${{ secrets.GARANT_ADMIN_PASSWORD }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: |
          # Create .env file from env-cloud template
          cp env-cloud .env

          # Replace placeholders with secret values
          sed -i "s/GARANT_ADMIN_PASSWORD=/GARANT_ADMIN_PASSWORD=${GARANT_ADMIN_PASSWORD}/" .env
          sed -i "s/CLIENT_ID=/CLIENT_ID=${CLIENT_ID}/" .env
