name: Retrieve secrets from secret repo
on:
  workflow_dispatch:

jobs:
  retrieve-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Environment
        env:
          GARANT_ADMIN_PASSWORD: '${{ secrets.GARANT_ADMIN_PASSWORD }}'
          CLIENT_ID: hopeitwork

        run: |
          chmod +x setup-env.sh  # Ensure the script is executable
          ./setup-env.sh  # Run the script
          echo "GARANT_ADMIN_PASSWORD: $GARANT_ADMIN_PASSWORD"

      - name: Debug
        run:
          ls -l
          cat .env
